### ISSUE TITLE
Document: Automated/convenient way to create and update reference data

### ISSUE THREAD

**Issue by jdries** [ESA-APEx/apex_documentation#21]
We need to somehow manage the reference data for benchmark scenario's.

When a user adds new scenario, the reference data does not yet exist. In that case, we could detect this and simply upload whatever we generated. The user would then be required to check if it is correct. 

When the scenario fails because the reference data needs an update, we would need something else?

**Comment by soxofaan** [comment]
made PR #22 to add docs

**Comment by soxofaan** [comment]
#22 was merged
