### ISSUE TITLE
AI43 - Create page of explaining the benefits of openEO and AP

### ISSUE THREAD

**Issue by JanssenBrm** [ESA-APEx/apex_documentation#7]
Add a section to the document, before the requirements, describing the benefits of the technologies we are promoting (openEO, AP). (MS1 - RID 18)

**Comment by JanssenBrm** [comment]
Hi @p3dr0 , @jdries  - This a friendly nudge to integrate this as part of the documentation.

**Comment by jdries** [comment]
@JanssenBrm  I see you found the PR, I suggest to simply merge it to close the action item. We simply reached the deadline, and the current version is better than nothing.
